# Generated by Django 5.2 on 2025-05-28 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscription_plan", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscriptionrequest",
            name="schedule_date",
        ),
    ]
