# Generated by Django 5.2 on 2025-05-28 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscription_plan", "0002_remove_subscriptionrequest_schedule_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscriptionrequest",
            name="schedule_time",
        ),
    ]
