# Generated by Django 5.2 on 2025-05-13 13:32

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sellrequest",
            name="additional_documents",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                help_text="Any additional documents (PDF/Image)",
                max_length=255,
                null=True,
                verbose_name="document",
            ),
        ),
        migrations.AlterField(
            model_name="sellrequest",
            name="insurance_document",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                help_text="Insurance document (PDF/Image)",
                max_length=255,
                null=True,
                verbose_name="document",
            ),
        ),
        migrations.AlterField(
            model_name="sellrequest",
            name="ownership_transfer",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                help_text="Ownership Transfer documents (PDF/Image)",
                max_length=255,
                null=True,
                verbose_name="document",
            ),
        ),
        migrations.AlterField(
            model_name="sellrequest",
            name="photo_back",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                help_text="Back view of vehicle",
                max_length=255,
                null=True,
                verbose_name="image",
            ),
        ),
        migrations.AlterField(
            model_name="sellrequest",
            name="photo_dashboard",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                help_text="Dashboard/Instrument cluster view",
                max_length=255,
                null=True,
                verbose_name="image",
            ),
        ),
        migrations.AlterField(
            model_name="sellrequest",
            name="photo_engine",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                help_text="Engine view",
                max_length=255,
                null=True,
                verbose_name="image",
            ),
        ),
        migrations.AlterField(
            model_name="sellrequest",
            name="photo_extras",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                help_text="Additional photos/modifications",
                max_length=255,
                null=True,
                verbose_name="image",
            ),
        ),
        migrations.AlterField(
            model_name="sellrequest",
            name="photo_front",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                help_text="Front view of vehicle",
                max_length=255,
                null=True,
                verbose_name="image",
            ),
        ),
        migrations.AlterField(
            model_name="sellrequest",
            name="photo_left",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                help_text="Left side view of vehicle",
                max_length=255,
                null=True,
                verbose_name="image",
            ),
        ),
        migrations.AlterField(
            model_name="sellrequest",
            name="photo_odometer",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                help_text="Odometer reading",
                max_length=255,
                null=True,
                verbose_name="image",
            ),
        ),
        migrations.AlterField(
            model_name="sellrequest",
            name="photo_right",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                help_text="Right side view of vehicle",
                max_length=255,
                null=True,
                verbose_name="image",
            ),
        ),
        migrations.AlterField(
            model_name="sellrequest",
            name="puc_certificate",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                help_text="Pollution Under Control Certificate (PDF/Image)",
                max_length=255,
                null=True,
                verbose_name="document",
            ),
        ),
        migrations.AlterField(
            model_name="sellrequest",
            name="registration_certificate",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                help_text="Vehicle Registration Certificate (PDF/Image)",
                max_length=255,
                null=True,
                verbose_name="document",
            ),
        ),
    ]
