# Generated by Django 5.2 on 2025-05-25 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_userprofile_profile_photo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="preferredLocation",
            new_name="preferred_location",
        ),
    ]
