# Generated by Django 5.2 on 2025-05-26 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_fields"),
        ("accounts", "0002_update_userprofile"),
    ]

    operations = []
