# Generated by Django 5.2 on 2025-06-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_preferred_location_completely"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="account_status",
            field=models.CharField(
                choices=[
                    ("unverified", "Unverified"),
                    ("active", "Active"),
                    ("suspended", "Suspended"),
                    ("deleted", "Deleted"),
                ],
                default="unverified",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="last_verification_sent",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="verification_attempts",
            field=models.IntegerField(default=0),
        ),
    ]
