# Generated by Django 5.2 on 2025-06-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_userprofile_manufacturer_userprofile_vehicle_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="manufacturer",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="vehicle_name",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="vehicle_type",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
