# Generated by Django 5.2 on 2025-06-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_userprofile_manufacturer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="manufacturer",
            field=models.IntegerField(blank=True, db_column="manufacturer", null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="vehicle_name",
            field=models.IntegerField(blank=True, db_column="vehicle_name", null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="vehicle_type",
            field=models.IntegerField(blank=True, db_column="vehicle_type", null=True),
        ),
    ]
