# Generated by Django 5.2 on 2025-06-07 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_add_phone_number'),
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle.manufacturer'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='vehicle_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle.vehiclemodel'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='vehicle_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle.vehicletype'),
        ),
    ]
