# Generated by Django 5.2 on 2025-06-03 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_fix_vehicle_fields"),
        ("vehicle", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="manufacturer",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="vehicle_name",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="vehicle_type",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="vehicle_model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="vehicle.vehiclemodel",
            ),
        ),
    ]
