# Generated by Django 5.2 on 2025-05-06 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="manufacturer_images/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VehicleType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="vehicle_types/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserVehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vehicle_type_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "manufacturer_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("model_name", models.CharField(blank=True, max_length=100, null=True)),
                ("registration_number", models.CharField(max_length=50, unique=True)),
                ("purchase_date", models.DateField(blank=True, null=True)),
                (
                    "vehicle_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="user_vehicles/"
                    ),
                ),
                ("color", models.CharField(blank=True, max_length=50)),
                ("year", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "mileage",
                    models.PositiveIntegerField(
                        blank=True, help_text="Kilometers driven", null=True
                    ),
                ),
                ("insurance_expiry", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicles",
                        to="accounts.userprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VehicleImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="user_vehicles/gallery/")),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("front", "Front View"),
                            ("back", "Back View"),
                            ("left", "Left Side"),
                            ("right", "Right Side"),
                            ("dashboard", "Dashboard"),
                            ("odometer", "Odometer"),
                            ("engine", "Engine"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("caption", models.CharField(blank=True, max_length=100)),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                (
                    "user_vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="vehicle.uservehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "-is_primary"],
            },
        ),
        migrations.CreateModel(
            name="VehicleModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="vehicle_models/"
                    ),
                ),
                (
                    "image_front",
                    models.ImageField(
                        blank=True, null=True, upload_to="vehicle_models/front/"
                    ),
                ),
                (
                    "image_back",
                    models.ImageField(
                        blank=True, null=True, upload_to="vehicle_models/back/"
                    ),
                ),
                (
                    "image_side",
                    models.ImageField(
                        blank=True, null=True, upload_to="vehicle_models/side/"
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="vehicle_models/thumbnails/"
                    ),
                ),
                (
                    "specs",
                    models.JSONField(
                        blank=True, default=dict, help_text="Technical specifications"
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "manufacturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vehicle.manufacturer",
                    ),
                ),
                (
                    "vehicle_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vehicle.vehicletype",
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "manufacturer")},
            },
        ),
    ]
