# Generated by Django 5.2 on 2025-06-11 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclemodel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='vehiclemodel',
            name='image_back',
        ),
        migrations.RemoveField(
            model_name='vehiclemodel',
            name='image_front',
        ),
        migrations.RemoveField(
            model_name='vehiclemodel',
            name='image_side',
        ),
        migrations.RemoveField(
            model_name='vehiclemodel',
            name='specs',
        ),
        migrations.RemoveField(
            model_name='vehiclemodel',
            name='thumbnail',
        ),
    ]
