# Generated by Django 5.2 on 2025-05-10 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("vehicle", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uservehicle",
            name="manufacturer_name",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="uservehicle",
            name="model_name",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="uservehicle",
            name="registration_number",
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="uservehicle",
            name="vehicle_type_name",
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="uservehicle",
            name="year",
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="vehicleimage",
            name="is_primary",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="vehicleimage",
            name="position",
            field=models.CharField(
                choices=[
                    ("front", "Front View"),
                    ("back", "Back View"),
                    ("left", "Left Side"),
                    ("right", "Right Side"),
                    ("dashboard", "Dashboard"),
                    ("odometer", "Odometer"),
                    ("engine", "Engine"),
                    ("other", "Other"),
                ],
                db_index=True,
                default="other",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="vehicleimage",
            name="upload_date",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="vehiclemodel",
            name="name",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name="uservehicle",
            index=models.Index(
                fields=["user", "registration_number"],
                name="vehicle_use_user_id_ac9a51_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="uservehicle",
            index=models.Index(
                fields=["manufacturer_name", "model_name"],
                name="vehicle_use_manufac_b7973f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="uservehicle",
            index=models.Index(fields=["year"], name="vehicle_use_year_d2e256_idx"),
        ),
        migrations.AddIndex(
            model_name="vehicleimage",
            index=models.Index(
                fields=["user_vehicle", "is_primary"],
                name="vehicle_veh_user_ve_16766b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="vehicleimage",
            index=models.Index(
                fields=["position", "is_primary"], name="vehicle_veh_positio_fa92fb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vehiclemodel",
            index=models.Index(fields=["name"], name="vehicle_veh_name_88f182_idx"),
        ),
        migrations.AddIndex(
            model_name="vehiclemodel",
            index=models.Index(
                fields=["manufacturer", "vehicle_type"],
                name="vehicle_veh_manufac_e80ffd_idx",
            ),
        ),
    ]
