# Generated by Django 5.2 on 2025-06-06 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cart", "0001_initial"),
        ("spare_parts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="part",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="spare_parts.sparepart"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="cart.order",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="part",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="spare_parts.sparepart"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together={("cart", "part")},
        ),
    ]
