# Generated by Django 5.2 on 2025-06-06 07:51

import cloudinary.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("vehicle", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PartCategory",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "image",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="image"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="spare_parts.partcategory",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Part Categories",
            },
        ),
        migrations.CreateModel(
            name="SparePart",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                ("part_number", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField()),
                ("features", models.TextField(blank=True)),
                ("specifications", models.JSONField(blank=True, default=dict)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "discounted_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("stock_quantity", models.PositiveIntegerField(default=0)),
                (
                    "availability_status",
                    models.CharField(
                        choices=[
                            ("in_stock", "In Stock"),
                            ("out_of_stock", "Out of Stock"),
                            ("pre_order", "Pre-Order"),
                            ("discontinued", "Discontinued"),
                        ],
                        default="in_stock",
                        max_length=20,
                    ),
                ),
                (
                    "main_image",
                    cloudinary.models.CloudinaryField(
                        max_length=255, verbose_name="image"
                    ),
                ),
                ("additional_images", models.JSONField(blank=True, default=list)),
                ("meta_title", models.CharField(blank=True, max_length=100)),
                ("meta_description", models.TextField(blank=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parts",
                        to="spare_parts.partcategory",
                    ),
                ),
                (
                    "manufacturers",
                    models.ManyToManyField(
                        related_name="spare_parts", to="vehicle.manufacturer"
                    ),
                ),
                (
                    "vehicle_models",
                    models.ManyToManyField(
                        related_name="spare_parts", to="vehicle.vehiclemodel"
                    ),
                ),
                (
                    "vehicle_types",
                    models.ManyToManyField(
                        related_name="spare_parts", to="vehicle.vehicletype"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PartReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.PositiveSmallIntegerField()),
                ("review_text", models.TextField()),
                ("purchase_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="spare_parts.sparepart",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("part", "user")},
            },
        ),
    ]
