# Generated by Django 5.2 on 2025-06-12 21:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spare_parts', '0002_distancepricingrule_partscart_partsorder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparepart',
            name='main_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
